---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
pipelines:
  pipeline:
    stages:
    - build_pip: {}
    - build_deploy: {}
stages:
  build_pip:
    workflows:
    - shared: {}
  build_deploy:
    workflows:
    - deploy: {}
workflows:
  deploy:
    description: |
      Deploys app using [Deploy to bitrise.io Step](https://devcenter.bitrise.io/en/getting-started/getting-started-with-android-apps.html#deploying-an-android-app-to-bitrise-io-53056).

      Next steps:
      - Check out [Getting started with Android apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-android-apps.html) for signing and deployment options.
      - [Set up code signing with *Android Sign* Step](https://devcenter.bitrise.io/en/code-signing/android-code-signing/android-code-signing-using-the-android-sign-step.html).
    before_run:
    - shared_config
    steps:
    - android-build@1: {}
    - cache-push@2: {}
  primary:
    description: |
      Runs tests.

      Next steps:
      - Check out [Getting started with Android apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-android-apps.html).
    steps:
    - activate-ssh-key@4: {}
    - git-clone@8: {}
    - restore-gradle-cache@1: {}
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-unit-test@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}
  shared:
    description: |
      Runs tests.

      Next steps:
      - Check out [Getting started with Android apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-android-apps.html).
    steps:
    - activate-ssh-key@4: {}
    - git-clone@8: {}
    - restore-gradle-cache@1: {}
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-lint@0: {}
    - android-unit-test@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}
  shared_config:
    steps:
    - pull-intermediate-files@1:
        inputs:
        - artifact_sources: build_pip.shared
meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: standard
app:
  envs:
  - opts:
      is_expand: false
    PROJECT_LOCATION: "."
  - opts:
      is_expand: false
    MODULE: app
  - opts:
      is_expand: false
    VARIANT: ''
  - opts:
      is_expand: false
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
